package com.sulzhenko.model;

public interface Constants {
    String ACTIVE = "active";
    String ACTIVE_STATUS = "active.status";
    String ACTIVITY_NAME = "activity_name";
    String ADD = "add";
    String ALL_CATEGORIES = "all categories";
    String AMOUNT_NONNEGATIVE = "amount.nonnegative";
    String ASC = "ASC";
    String CATEGORY_NAME = "category_name";
    String CATEGORY_OF_ACTIVITY = "category of activity";
    String DEACTIVATED = "deactivated";
    String DESC = "DESC";
    String DESCENDING = "descending";
    String DIFFERENT_PASSWORDS = "different.passwords";
    String EMPTY_LOGIN = "empty.login";
    String EMPTY_PASSWORD = "empty.password";
    String ERROR = "error";
    String FILTER = "filter";
    String INACTIVE = "inactive";
    String LOGIN = "login";
    String NAME_OF_ACTIVITY = "name of activity";
    String NO_OF_PAGES = "noOfPages";
    String NUMBER_OF_USERS = "number of users";
    String OFFSET = "offset";
    String ORDER = "order";
    String PAGE = "page";
    String PARAMETER = "parameter";
    String PASSWORD = "password";
    String PENDING_ADDING = "pending.adding";
    String PENDING_REMOVING = "pending.removing";
    String QUANTITY = "quantity";
    String RECORDS = "records";
    String REMOVE = "remove";

    String SYSTEM_USER = "system user";
    String USER = "user";
    String USER_HAS_NO_ACTIVITY ="user.has.no.activity";
    String UNKNOWN_ERROR = "unknown.error";
    String UPDATED = "updated";
    String UTF8 = "UTF-8";
    String WRONG_ACTION = "wrong.action";
    String WRONG_ACTIVITY = "wrong.activity";
    String WRONG_CATEGORY = "wrong.category";
    String WRONG_LOGIN = "wrong.login";
    String WRONG_PASSWORD = "wrong.password";
    String WRONG_ROLE = "wrong.role";
    String WRONG_STATUS = "wrong.status";
}
